# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exercise_pb2 as exercise__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exercise_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExerciseServiceStub(object):
    """[Service] 운동 분석 및 세션 관리 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAnalysis = channel.unary_unary(
                '/ExerciseService/StartAnalysis',
                request_serializer=exercise__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=exercise__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.CompleteAnalysis = channel.unary_unary(
                '/ExerciseService/CompleteAnalysis',
                request_serializer=exercise__pb2.SessionCompleteRequest.SerializeToString,
                response_deserializer=exercise__pb2.SessionCompleteResponse.FromString,
                _registered_method=True)
        self.SavePoseDataBatch = channel.unary_unary(
                '/ExerciseService/SavePoseDataBatch',
                request_serializer=exercise__pb2.PoseDataBatchRequest.SerializeToString,
                response_deserializer=exercise__pb2.PoseDataResponse.FromString,
                _registered_method=True)
        self.GetFinalPoseData = channel.unary_unary(
                '/ExerciseService/GetFinalPoseData',
                request_serializer=exercise__pb2.SessionRequest.SerializeToString,
                response_deserializer=exercise__pb2.PoseDataList.FromString,
                _registered_method=True)


class ExerciseServiceServicer(object):
    """[Service] 운동 분석 및 세션 관리 서비스
    """

    def StartAnalysis(self, request, context):
        """1. 운동 세션 시작 요청 (Spring -> FastAPI)
        기존 StartAnalysis를 ExercisesRequestDto 규격에 맞춰 고도화
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAnalysis(self, request, context):
        """2. 운동 세션 종료 및 분석 결과 전송 (FastAPI -> Spring)
        PUT /complete 요청에 대응하며, FastAPI가 분석을 마치고 스프링에 결과를 보고함
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePoseDataBatch(self, request, context):
        """3. 분석 결과 배치 저장 (FastAPI -> Spring)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinalPoseData(self, request, context):
        """4. 최종 결과 조회 (Spring -> FastAPI)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExerciseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAnalysis,
                    request_deserializer=exercise__pb2.AnalyzeRequest.FromString,
                    response_serializer=exercise__pb2.AnalyzeResponse.SerializeToString,
            ),
            'CompleteAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAnalysis,
                    request_deserializer=exercise__pb2.SessionCompleteRequest.FromString,
                    response_serializer=exercise__pb2.SessionCompleteResponse.SerializeToString,
            ),
            'SavePoseDataBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePoseDataBatch,
                    request_deserializer=exercise__pb2.PoseDataBatchRequest.FromString,
                    response_serializer=exercise__pb2.PoseDataResponse.SerializeToString,
            ),
            'GetFinalPoseData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinalPoseData,
                    request_deserializer=exercise__pb2.SessionRequest.FromString,
                    response_serializer=exercise__pb2.PoseDataList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExerciseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ExerciseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExerciseService(object):
    """[Service] 운동 분석 및 세션 관리 서비스
    """

    @staticmethod
    def StartAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExerciseService/StartAnalysis',
            exercise__pb2.AnalyzeRequest.SerializeToString,
            exercise__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExerciseService/CompleteAnalysis',
            exercise__pb2.SessionCompleteRequest.SerializeToString,
            exercise__pb2.SessionCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePoseDataBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExerciseService/SavePoseDataBatch',
            exercise__pb2.PoseDataBatchRequest.SerializeToString,
            exercise__pb2.PoseDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFinalPoseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ExerciseService/GetFinalPoseData',
            exercise__pb2.SessionRequest.SerializeToString,
            exercise__pb2.PoseDataList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
