# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exercise.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exercise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xercise.proto\"M\n\x0e\x41nalyzeRequest\x12\x13\n\x0b\x65xercise_id\x18\x01 \x01(\x03\x12\x12\n\nyoutube_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\x03\"\"\n\x0f\x41nalyzeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x03\"4\n\x0cPoseDataList\x12$\n\tpose_data\x18\x01 \x03(\x0b\x32\x11.PoseDataResponse\"C\n\x0fPoseDataRequest\x12\x15\n\rtimestamp_sec\x18\x01 \x01(\x01\x12\x19\n\x11joint_coordinates\x18\x02 \x01(\t\"O\n\x14PoseDataBatchRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x03\x12#\n\tpose_data\x18\x02 \x03(\x0b\x32\x10.PoseDataRequest\"i\n\x10PoseDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\x03\x12\x15\n\rtimestamp_sec\x18\x03 \x01(\x01\x12\x19\n\x11joint_coordinates\x18\x04 \x01(\t2\xb8\x01\n\x0f\x45xerciseService\x12\x32\n\rStartAnalysis\x12\x0f.AnalyzeRequest\x1a\x10.AnalyzeResponse\x12\x32\n\x10GetFinalPoseData\x12\x0f.SessionRequest\x1a\r.PoseDataList\x12=\n\x11SavePoseDataBatch\x12\x15.PoseDataBatchRequest\x1a\x11.PoseDataResponseB%\n\x12\x63om.shadowfit.grpcB\rExerciseProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exercise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.shadowfit.grpcB\rExerciseProtoP\001'
  _globals['_ANALYZEREQUEST']._serialized_start=18
  _globals['_ANALYZEREQUEST']._serialized_end=95
  _globals['_ANALYZERESPONSE']._serialized_start=97
  _globals['_ANALYZERESPONSE']._serialized_end=131
  _globals['_SESSIONREQUEST']._serialized_start=133
  _globals['_SESSIONREQUEST']._serialized_end=169
  _globals['_POSEDATALIST']._serialized_start=171
  _globals['_POSEDATALIST']._serialized_end=223
  _globals['_POSEDATAREQUEST']._serialized_start=225
  _globals['_POSEDATAREQUEST']._serialized_end=292
  _globals['_POSEDATABATCHREQUEST']._serialized_start=294
  _globals['_POSEDATABATCHREQUEST']._serialized_end=373
  _globals['_POSEDATARESPONSE']._serialized_start=375
  _globals['_POSEDATARESPONSE']._serialized_end=480
  _globals['_EXERCISESERVICE']._serialized_start=483
  _globals['_EXERCISESERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
